In [ ]:
from sklearn.neural_network import MLPClassifier
X = [[0., 0.], [0., 1.]]
y = [0, 1]
clf = MLPClassifier(hidden_layer_sizes=(4), random_state=0)
clf.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=4, random_state=0)

In [ ]:
print('la forme du perceptron',[coef.shape for coef in clf.coefs_])

la forme du perceptron [(2, 4), (4, 1)]


In [ ]:
 clf.predict([[2., 2.]])

array([1])

In [ ]:
clf.predict([[-1., -2.]])

array([0])

In [ ]:
 print('les coefficients', clf.coefs_)

les coefficients [array([[ 1.40189095e-03,  2.51687364e-01,  5.41845557e-02,
         5.79678815e-04],
       [ 6.62768895e-02,  4.86921079e-01, -3.04906881e-01,
         6.06259463e-01]]), array([[ 0.33959501],
       [ 1.18905791],
       [-0.84729469],
       [-0.73983565]])]


In [ ]:
print('le poid des bais', clf.intercepts_)

le poid des bais [array([ 1.13033621, -0.03798289,  0.41832856, -0.13406003]), array([-0.88093148])]


In [ ]:
X = [[0., 0.], [0., 1.], [1, 1],[1, 0]]
y = [0, 1, 0, 1]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(4), random_state=0)
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=4, random_state=0, solver='lbfgs')

In [ ]:
print('x1=0, x2=0, y= ', clf.predict([[0,0]]))
print('x1=0, x2=1, y= ',clf.predict([[0,1]]))
print('x1=1, x2=0, y= ',clf.predict([[1,0]]))
print('x1=1, x2=1, y= ',clf.predict([[1,1]]))

x1=0, x2=0, y=  [0]
x1=0, x2=1, y=  [1]
x1=1, x2=0, y=  [1]
x1=1, x2=1, y=  [0]


In [ ]:
clf.predict([[-1., -2.]])

array([0])

In [ ]:
print('x1=0, x2=0, y= ', clf.predict([[-1., -2.]]))
print('x1=0, x2=1, y= ',clf.predict([[-1., -2.]]))
print('x1=1, x2=0, y= ',clf.predict([[-1., -2.]]))
print('x1=1, x2=1, y= ',clf.predict([[-1., -2.]]))

In [ ]:
from sklearn.neural_network import MLPClassifier
X = [[0., 0.], [0., 1.]]
y= [[1., 1.], [1., 0.]]
xtest = [[2,2],[-1,-2]]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(4), random_state=0)
yperd=clf.fit(X, y)
print(yperd)
print(clf.coefs_)
print(clf.intercepts_)
print('x1=0, x2=0, y= ', clf.predict([[0,0]]))
print('x1=0, x2=1, y= ',clf.predict([[0,1]]))
print('x1=1, x2=0, y= ',clf.predict([[1,0]]))
print('x1=1, x2=1, y= ',clf.predict([[1,1]]))

MLPClassifier(alpha=1e-05, hidden_layer_sizes=4, random_state=0, solver='lbfgs')
[array([[ 0.0960717 ,  0.4235223 ,  0.20225247,  0.08833628],
       [-2.78235813,  3.75355241, -1.46982614,  0.49275522]]), array([[ 2.36623184,  3.32823398],
       [ 0.97836634, -2.85399279],
       [-0.25846047,  0.55187286],
       [ 1.78139876, -2.3996955 ]])]
[array([ 3.34019217,  0.16198951, -0.10000173, -0.01171141]), array([ 4.69908029, -0.40475395])]
x1=0, x2=0, y=  [[1 1]]
x1=0, x2=1, y=  [[1 0]]
x1=1, x2=0, y=  [[1 1]]
x1=1, x2=1, y=  [[1 0]]


In [ ]:
print('x1=0, x2=0, y= ', clf.predict([[0,0]]))
print('x1=0, x2=1, y= ',clf.predict([[0,1]]))
print('x1=1, x2=0, y= ',clf.predict([[1,0]]))
print('x1=1, x2=1, y= ',clf.predict([[1,1]]))

x1=0, x2=0, y=  [0]
x1=0, x2=1, y=  [1]
x1=1, x2=0, y=  [1]
x1=1, x2=1, y=  [0]


In [ ]:
import time
start_time = time.time()
#--  Apprentissage
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score

#from sklearn.model_selection import HalvingGridSearchCV
# Chargement des données
iris = datasets.load_iris()
X = iris.data
y = iris.target
trainX, testX, trainY, testY = train_test_split(X, y, test_size = 0.2)
end_time = time.time()
print('Dataset Sizes : ', X.shape, y.shape)
print('temps ecoule = '+str(end_time - start_time))

Dataset Sizes :  (150, 4) (150,)
temps ecoule = 0.005806446075439453


In [ ]:
print('**************(10)*********************************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10), random_state=0,)
clf.fit(X, y)
y_pred = clf.predict(testX)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100)*****************************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100), random_state=0,)
clf.fit(X, y)
y_pred = clf.predict(testX)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100, 150)************************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100, 150), random_state=0,)
clf.fit(X, y)
y_pred = clf.predict(testX)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100, 150, 200)*******************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100, 200), random_state=0,)
clf.fit(X, y)
y_pred = clf.predict(testX)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100, 150, 200, 300)*************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100, 150, 200, 300), random_state=0,)
clf.fit(X, y)
y_pred = clf.predict(testX)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))

In [ ]:
print("Loss : ", clf.loss_)

Loss :  0.0008444976128401261


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(trainX)
trainX_scaled = scaler.transform(trainX)
testX_scaled = scaler.transform(testX)

In [ ]:
print('**************(10)*********************************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10), random_state=0,)
clf.fit(trainX_scaled, trainY)
y_pred = clf.predict(testX_scaled)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100)*****************************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100), random_state=0,)
clf.fit(trainX_scaled, trainY)
y_pred = clf.predict(testX_scaled)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100, 150)************************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100, 150), random_state=0,)
clf.fit(trainX_scaled, trainY)
y_pred = clf.predict(testX_scaled)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100, 150, 200)*******************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100, 200), random_state=0,)
clf.fit(trainX_scaled, trainY)
y_pred = clf.predict(testX_scaled)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))
print('**************(10, 100, 150, 200, 300)*************************')
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(10, 100, 150, 200, 300), random_state=0,)
clf.fit(trainX_scaled, trainY)
y_pred = clf.predict(testX_scaled)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))

In [ ]:
start_time = time.time()
clf = svm.SVC(kernel='poly', C= 100)
#clf = MLPClassifier(hidden_layer_sizes=(100, 200, 300), random_state=0,)
clf.fit(X, y)
y_pred = clf.predict(testX)
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
end_time = time.time()
print('temps ecoule = '+str(end_time - start_time))

Accuracy: 0.97
temps ecoule = 0.024467945098876953


In [ ]:
from scipy.optimize import lbfgsb
from scipy.optimize import OptimizeResult

c=('adam', 'sgd', 'lbfgs')
for i in c: 
  print('**************(10)*********************************************')
  start_time = time.time()
  clf = MLPClassifier(solver= i, hidden_layer_sizes=(10), random_state=0)
  clf.fit(trainX_scaled, trainY)
  y_pred = clf.predict(testX_scaled)
  print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)),i)
  end_time = time.time()
  print('temps ecoule = '+str(end_time - start_time))
  print('**************(10, 100)*****************************************')
  start_time = time.time()
  clf = MLPClassifier(solver= i,hidden_layer_sizes=(10, 100), random_state=0)
  clf.fit(trainX_scaled, trainY)
  y_pred = clf.predict(testX_scaled)
  print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)),i)
  end_time = time.time()
  print('temps ecoule = '+str(end_time - start_time))
  print('**************(10, 100, 150)************************************')
  start_time = time.time()
  clf = MLPClassifier(solver= i,hidden_layer_sizes=(10, 100, 150), random_state=0)
  clf.fit(trainX_scaled, trainY)
  y_pred = clf.predict(testX_scaled)
  print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)),i)
  end_time = time.time()
  print('temps ecoule = '+str(end_time - start_time))
  print('**************(10, 100, 150, 200)*******************************')
  start_time = time.time()
  clf = MLPClassifier(solver= i,hidden_layer_sizes=(10, 100, 200), random_state=0,)
  clf.fit(trainX_scaled, trainY)
  y_pred = clf.predict(testX_scaled)
  print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)),i)
  end_time = time.time()
  print('temps ecoule = '+str(end_time - start_time))
  print('**************(10, 100, 150, 200, 300)*************************')
  start_time = time.time()
  clf = MLPClassifier(solver= i,hidden_layer_sizes=(10, 100, 150, 200, 300), random_state=0,)
  clf.fit(trainX_scaled, trainY)
  y_pred = clf.predict(testX_scaled)
  print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)),i)
  end_time = time.time()
  print('temps ecoule = '+str(end_time - start_time))


In [8]:
from keras.datasets import mnist 
from sklearn.multiclass import OneVsRestClassifier 
from sklearn.svm import SVC 
import numpy as np 
from sklearn.model_selection import GridSearchCV 
from sklearn.neural_network import MLPClassifier 
import time 
start_time = time.time()
# chargement des données MNIST
data = mnist.load_data()
(X_train, y_train), (X_test, y_test) = data 

# chargement des données 3D -> 2D
X_train_flat = X_train.reshape(60000, -1)
X_test_flat = X_test.reshape(10000, -1)
#Application un GridSearchCV pour trouver la meilleurs configuration 
param_grid = {
    'hidden_layer_sizes': [2, 3, 4, 5],
    'activation': ['logistic', 'relu'],
    'solver': ['sgd', 'adam', 'lbfgs'],
    'learning_rate': ['constant','adaptive'],
    'alpha': [0.0001,0.001],  
    }
clf = GridSearchCV(MLPClassifier(), param_grid,  cv=5, n_jobs= 4, verbose=1)
clf.fit(X_train_flat, y_train)
y_pred= clf.predict(X_test_flat)
print("le meilleur score: "+ str(clf.best_estimator_.score(X_test_flat, y_test)))
print("la meilleurs configuration est:"+str(clf.best_params))

Fitting 5 folds for each of 96 candidates, totalling 480 fits


/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:703: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


KeyboardInterrupt: ignored

In [11]:
from keras.datasets import mnist 
from sklearn.multiclass import OneVsRestClassifier 
from sklearn.svm import SVC 
import numpy as np 
from sklearn.model_selection import GridSearchCV 
from sklearn.neural_network import MLPClassifier 
import time 
start_time = time.time()
# chargement des données 
data = mnist.load_data()
(X_train, y_train), (X_test, y_test) = data 

# chargement des données 3D -> 2D
X_train_flat = X_train.reshape(60000, -1)
X_test_flat = X_test.reshape(10000, -1)
#appliquons un GridSearchCV pour trouver la meilleur configuration possible 

start_time=time.time()
clf= MLPClassifier(hidden_layer_sizes=(50,),max_iter=10, alpha=1e-4, solver='sgd',verbose=10)
clf.fit(X_train_flat, y_train)
end_time = time.time()
print("Test set score: {:.2f}".format(clf.score(X_test_flat, y_test)))
print('temps ecoule = {:.2f} '.format(end_time - start_time))

Iteration 1, loss = 2.54139698
Iteration 2, loss = 2.02865496
Iteration 3, loss = 1.84548830
Iteration 4, loss = 1.75407252
Iteration 5, loss = 1.68551470
Iteration 6, loss = 1.60156621
Iteration 7, loss = 1.49499561
Iteration 8, loss = 1.42350886
Iteration 9, loss = 1.36442088
Iteration 10, loss = 1.32365487
Test set score: 0.54
temps ecoule = 14.24 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
